# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(533, 399)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 60, 481, 41))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.fileButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.fileButton.setObjectName("fileButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fileButton)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 481, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog) # mp3
        self.pushButton_2.setGeometry(QtCore.QRect(200, 140, 114, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setGeometry(QtCore.QRect(330, 140, 114, 32))
        self.clearButton.setObjectName("clearButton")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(20, 280, 471, 91))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 469, 89))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.showMsg = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.showMsg.setText("")
        self.showMsg.setObjectName("showMsg")
        self.verticalLayout.addWidget(self.showMsg)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.showDone = QtWidgets.QLabel(Dialog)
        self.showDone.setGeometry(QtCore.QRect(332, 230, 151, 24))
        self.showDone.setText("")
        self.showDone.setObjectName("showDone")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(20, 230, 301, 26))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 140, 111, 31))
        self.pushButton.setObjectName("pushButton") # mp4

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fileButton.setText(_translate("Dialog", "儲存位置"))
        self.label.setText(_translate("Dialog", "選擇位置"))
        self.pushButton_2.setText(_translate("Dialog", "下載mp3"))
        self.clearButton.setText(_translate("Dialog", "清除"))
        self.pushButton.setText(_translate("Dialog", "下載mp4"))
